= Techdegree project 10 : Recipes
:experimental:
:source-highlighter: coderay
:toc:
:toclevels: 5
:toc-placement: preamble
:sectnums:
:main_package: link:./src/main/java/com/techdegree/
:test_package: link:./src/test/java/com/techdegree
:ItemValidator: {main_package}validator/ItemValidator.java[ItemValidator]
:ValidItem: {main_package}validator/ValidItem.java[ValidItem]
:CustomUserDetailsService: {main_package}service/CustomUserDetailsService.java[CustomUserDetailsService]
:IngredientService: {main_package}service/IngredientService.java[IngredientService]
:StepService: {main_package}service/StepService.java[StepService]
:ItemService: {main_package}service/ItemService.java[ItemService]
:RecipeService: {main_package}service/RecipeService.java[RecipeService]
:RecipeServiceImpl: {main_package}service/RecipeServiceImpl.java[RecipeServiceImpl]
:IngredientServiceImpl: {main_package}service/IngredientServiceImpl.java[IngredientServiceImpl]
:ItemServiceImpl: {main_package}service/ItemServiceImpl.java[ItemServiceImpl]
:StepServiceImpl: {main_package}service/StepServiceImpl.java[StepServiceImpl]
:DataLoader: {main_package}DataLoader.java[DataLoader]
:Application: {main_package}Application.java[Application]
:BaseEntity: {main_package}model/BaseEntity.java[BaseEntity]
:User: {main_package}model/User.java[User]
:RoleClass: {main_package}model/Role.java[Role]
:RecipeCategory: {main_package}model/RecipeCategory.java[RecipeCategory]
:Ingredient: {main_package}model/Ingredient.java[Ingredient]
:Item: {main_package}model/Item.java[Item]
:Step: {main_package}model/Step.java[Step]
:Recipe: {main_package}model/Recipe.java[Recipe]
:RecipeDaoImpl: {main_package}dao/RecipeDaoImpl.java[RecipeDaoImpl]
:RoleDao: {main_package}dao/RoleDao.java[RoleDao]
:UserDao: {main_package}dao/UserDao.java[UserDao]
:StepDao: {main_package}dao/StepDao.java[StepDao]
:ItemDao: {main_package}dao/ItemDao.java[ItemDao]
:IngredientDao: {main_package}dao/IngredientDao.java[IngredientDao]
:RecipeDao: {main_package}dao/RecipeDao.java[RecipeDao]
:FavoriteRecipesDao: {main_package}dao/FavoriteRecipesDao.java[FavoriteRecipesDao]
:FlashMessage: {main_package}web/FlashMessage.java[FlashMessage]
:LoginController: {main_package}web/controller/LoginController.java[LoginController]
:RecipeController: {main_package}web/controller/RecipeController.java[RecipeController]
:IndexRedirectController: {main_package}web/controller/IndexRedirectController.java[IndexRedirectController]
:WebConstants: {main_package}web/WebConstants.java[WebConstants]
:RecipeEventHandler: {main_package}handler/RecipeEventHandler.java[RecipeEventHandler]
:RestConfig: {main_package}config/RestConfig.java[RestConfig]
:AppConfig: {main_package}config/AppConfig.java[AppConfig]
:SecurityConfig: {main_package}config/SecurityConfig.java[SecurityConfig]
:TemplateConfig: {main_package}config/TemplateConfig.java[TemplateConfig]
:RecipeCategoryTest: {test_package}/model/RecipeCategoryTest.java[RecipeCategoryTest]
:RecipeDaoTest: {test_package}/dao/RecipeDaoTest.java[RecipeDaoTest]
:RecipeServiceTest: {test_package}/service/RecipeServiceTest.java[RecipeServiceTest]
:IndexRedirectControllerTest: {test_package}/web/controller/IndexRedirectControllerTest.java[IndexRedirectControllerTest]
:RecipeControllerItTest: {test_package}/web/controller/RecipeControllerItTest.java[RecipeControllerItTest]
:RecipeControllerTest: {test_package}/web/controller/RecipeControllerTest.java[RecipeControllerTest]
:build_gradle: link:./build.gradle[build.gradle]
:main_resources: link:./src/main/resources/
:templates: {main_resources}templates
:application_properties: {main_resources}application.properties[application.properties]
:signup_html: {templates}/signup.html[signup.html]
:edit_html: {templates}/edit.html[edit.html]
:login_html: {templates}/login.html[login.html]
:index_html: {templates}/index.html[index.html]
:detail_html: {templates}/detail.html[detail.html]
:layout_html: {templates}/layout.html[layout.html]
:profile_html: {templates}/profile.html[profile.html]
:app_js: {main_resources}/static/assets/js/app.js[app.js]
:coverage_report_tar_gz: link:./misc/coverage-report.tar.gz[coverage-report.tar.gz]

toc::[]

[[eclipse]]
== Eclipse Installation Instructions

Under Construction.

// Links

== Tasks


=== Task 1

Create model classes, DAO interfaces, services,
and add unit tests to components.
Determine test coverage using a code coverage tool
and ensure your tests cover of at least 60% of your code.

---

[[task-1-model]]
==== Model

Model classes created are:

* {Ingredient}
* {Item}
* {Recipe}
* {RoleClass}
* {Step}
* {User}

Some of them inherit {BaseEntity}, which is the `@MappedSuperClass`
that has `@Id id` and `@Version version` fields, that are
repeated in child classes.

{RecipeCategory} enum is used in {Recipe} class as `@Enumerated` field.

[[task-1-dao]]
==== DAO

DAO interfaces are created as Spring-Data `CrudRepository`-ies:

.Recipe related DAOs:
** {RecipeDao}
** {FavoriteRecipesDao}
** {RecipeDaoImpl}

.User related DAOs:
** {RoleDao}
** {UserDao}

.Other DAOs
* {IngredientDao}
* {ItemDao}
* {StepDao}

All {User} related DAOs are not exposed to REST API.

{FavoriteRecipesDao} is interface that allows us to add custom
methods to Spring-Data DAOs. And {RecipeDaoImpl} is the class that
implements {FavoriteRecipesDao} and defines manually defined
methods (For now only method listing favorite recipes for user).

[[task-1-service]]
==== Service

Service layer implementations do not have anything in particular,
except repeating commands at DAO layer:

* {CustomUserDetailsService}
* {IngredientService}
* {IngredientServiceImpl}
* {ItemService}
* {ItemServiceImpl}
* {RecipeService}
* {RecipeServiceImpl}
* {StepService}
* {StepServiceImpl}

Most of them repeat commands at DAO layer with few exceptions:

{RecipeDao} has significantly different `save` method that takes
into consideration that recipe has favorites and owner, see
related <<favorites, Favorites>> and <<recipe_owner, Recipe Owner>>
sections for more:

{CustomUserDetailsService} `implements UserDetailsService` and is very
common service that has `loadUserByUsername` method

[[task-1-coverage]]
==== Coverage

Coverage report is in gzipped file called
{coverage_report_tar_gz}

It was generated after I created configuration in
Intellijidea with
all tests and after running it I saved coverage and
gzipped it, because it has too many files. Later
I will try to create task in Gradle, but for now
that is best I can do.

=== Task 2
Using the supplied files, create the template for the recipe list page.
Use the following requirements list to ensure all functionality
is included in the recipe list page.

Recipes:

. <<favorites, Favorites>>
+
Displays a list of recipes by name and indicates
with a heart icon whether a user has favorited the recipe

. <<filter_by_category, Filter By Category>>
+
Allows the user to filter the list by the selected category

. <<add-new-recipe, Add New Recipe>>
+
Allows the user to add a new recipe

. <<user_account_page, User Account Page>>
+
A user must have an account

. <<edit_and_delete_recipe, Edit and Delete Recipe>>
+
Allows the user to edit or delete a recipe

. <<recipe_owner, Recipe Owner>>
+
A user must own the recipe

---

[[favorites]]
==== Favorites

Displays a list of recipes by name and indicates
with a heart icon whether a user has favorited the recipe

---

Recipes are displayed at the main page with the address

```
http://localhost:8080/
http://localhost:8080/recipes
http://localhost:8080/recipes/
```

{IndexRedirectController} takes care of redirecting from
both "/" and "/recipes" pages to "/recipes/" that is mapped
in {RecipeController}. There is probably a better way. But
I'll leave it for now as is. The functionality is tested in
{IndexRedirectControllerTest}

In order to show whether recipe is favorite for user we
generate `List<Recipe> favoriteRecipesWithNullsForNonFavorites`
that has exactly the same
size as all recipes printed, but on the places where
recipe is favorite for user, it contains recipe, and
elsewhere is `null`. This list is passed along with all recipes
to `Model`.

The list to be passed is generated in a
[java]`RecipeController.generateFavoritesWithNullsForNonFavoritesList`
method. And because of that is tested separately in
[java]`@Test favoritesWithNonNullsListIsGeneratedCorrectly` in
{RecipeControllerTest}

Simple list with favorite recipes for users is generated at DAO
level at customized {RecipeDaoImpl} using simple SQL query. It was
rather problematic for me to write Spring Query in annotation to
some method in {RecipeDao}, that is why I decided to make custom
implementation for now.

The function returning favorite recipes at DAO level is tested in
{RecipeDaoTest} in `findAllFavoritesReturnsOneFavoriteRecipeWithDataLoader`
test.

In the REST API for now it is impossible to get favorite recipes

This can be done in many different ways, but I decided to leave it so.

[[filter_by_category]]
==== Filter By Category

Allows the user to filter the list by the selected category

---

[[filter_by_category_usage]]
===== Usage

In the {DataLoader} for now 5 recipes are added, one for each category.
They are all have "tags" that can be clicked and user will be redirected
to the index page sorted by selected category tag:

```
/recipes/?category=name
```

There is also JavaScript function in {app_js} file
that is executed when `<select>`
element is changed. It redirects to index page filtered
by category.

[[filter_by_category_impl_details]]
===== Implementation Details

Implementation starts on model layer in {RecipeCategory}
`enum`. I introduced new methods `getRecipeCategoryWithHtmlName`
that returns `RecipeCategory.NONE` or `RecipeCategory`
found by member `htmlName`.

This method is tested in {RecipeCategoryTest}
`allRecipeCategoriesCanBeFoundByName`.

At *DAO* level I introduced Spring Query method called
`findByRecipeCategory` that comes from Spring and returns
`List<Recipe>` with `RecipeCategory` passed in argument.

This is tested in {RecipeDaoTest}
`listOfRecipesReturnedWhenFindByRecipeCategoryIsCalled`.

At *Service* layer I introduced in {RecipeService} and
implemented in {RecipeServiceImpl} `findByRecipeCategoryName`

I didn't test that because it directly returns result of
`RecipeDao.findByRecipeCategory` with argument as a result
of `RecipeCategory.getRecipeCategoryWithHtmlName`. It may be
not a good idea to put this functionality on *Service* layer, but
I decided to leave it here.

At *Controller* layer in {RecipeController}
`filterByCategory` method was introduced, that is passing
to `Model.attribute` "recipes" not all recipes, but the
ones `recipeService.findByCategoryName` returns. Argument
is query parameter. It comes from JavaScript or from tag anchor,
see <<filter_by_category_usage, Usage>>.

Also here is "selectedCategory" attribute is added to `Model`
because we want to display selected option on the redirected
page.

This functionality is tested in {RecipeControllerTest}
`recipesCanBeListedByCategoryOnIndexPage` test.


[[add-new-recipe]]
==== Add New Recipe

Allows the user to add a new recipe

---

New recipe can be added from the home page
by pressing "Add Recipe" button.

After pressing that button page `/recipes/add-new` is generated.
Template {edit_html} is used for both `/recipes/add-new` and
`/recipes/edit/id`, with the difference that `new Recipe` object
is passed to `Model` when `/recipes/add-new` is generated, and
`Recipe` from database is passed to `Model` when `/recipes/edit/id`
page is generated.

I made a try to re-use some code by creating
`addAttributesToModelForBothEditAndAddNewPages`. Don't know
whether that was a good idea or not, but I tried.

I also tried to use the same method `saveRecipe` for
both adding new recipe POST request and updating
already existing recipe.


[[user_account_page]]
==== User Account Page

A user must have an account

---

I guess by that is meant that user has to be logged?
Anyway, user is saved in database, for now
user registration is under construction

[[edit_and_delete_recipe]]
==== Edit and Delete Recipe

Allows the user to edit or delete a recipe

---

For now user can delete recipe, without any problems.
No restrictions on that. About edit, the same policy
applies, see section about saving recipe above.

[[recipe_owner]]
==== Recipe Owner

A user must own the recipe

---

When we save recipe we set recipe's owner.
The responsible field for this relationship is
`@ManyToOne Recipe.owner` on the {Recipe} side,
and `@OneToMany User.ownedRecipes` on the {User} side.
The relationship is determined by foreign_key
`owner_id` in the recipes table.

When Recipe is updated, we get the owner from database.

All functionality was moved by me to
service layer in `RecipeService.save` method, that
takes care not only about the owner of recipe, but
also sets favorite recipes from database, and
set `Recipe.ingredients[i].items` because with the
POST request we set only item id-s.

Related tests can be found in Mock-test in
{RecipeServiceTest} class:

* `savingNewRecipeSetsOwner`
* `updatingRecipeDoesNotChangeOwner`

Integration tests in {RecipeControllerItTest} are checking
recipe owner consistency as well. See tests:

* `updatingRecipeWithAllValidFieldsWorks`
* `savingNewRecipeWithAllValidFieldsWorks`
* `deletingRecipeShouldBePossible`




